### ISSUE TITLE
关于连续定位问题

### ISSUE THREAD

**Issue by tichaun** [waliu/cordova-plugin-gaodelocation-chenyu#1]
首先恭喜作者本插件被ionic官方收录，期待作者可以吧连续定位功能添加进去

**Comment by waliu** [comment]
好的。近期考虑加入

**Comment by yinglight** [comment]
希望赶紧有

**Comment by EminentNee** [comment]
您好 现在我遇到了一个问题是我们的移动设备长时间连续定位的时候会出现定位失败的情况，获取的坐标也是上一次定位成功的坐标，现在我们只能在出现这个问题的时候只能重启设备，麻烦能不能告诉我们怎样解决这个移动设备24小时定位的问题。谢谢

**Comment by Dongsipan** [comment]
请问何时能够添加持续定位功能

**Comment by waliu** [comment]
2.0.0

**Comment by waliu** [comment]
2.0.5版本

**Comment by waliu** [comment]
@Dongsipan

**Comment by waliu** [comment]
@EminentNee

**Comment by waliu** [comment]
$ cordova plugin add https://github.com/waliu/cordova-plugin-gaodelocation-chenyu  --variable  ANDROID_API_KEY=your android key --variable  IOS_API_KEY=your ios key
已经增加了持续定位
