### ISSUE TITLE
Android定位出来的地址和经纬度偏差太大

### ISSUE THREAD

**Issue by AlwaysLoveme** [waliu/cordova-plugin-gaodelocation-chenyu#16]
环境：
1. android 8.1.0
2. ionic  4.11.2
定位结果：
`
{
accuracy: 30
adcode: "310112"
address: "上海市闵行区万里路3482号靠近上海市科技创业中心闵行基地"
backtime: 1579426511878
bearing: 0
city: "上海市"
citycode: "021"
country: "中国"
district: "闵行区"
latitude: 31.078707
longitude: 121.523285
poi: "上海市科技创业中心闵行基地"
province: "上海市"
satellites: 0
status: "定位成功"
time: 1579426512784
type: 5

}
`
其中address和经纬度偏差特别大。。请问是咋回事

**Comment by waliu** [comment]
定位插件采用的哪个版本，
1.在项目中 输入命令 cordova plugin ls
2. 查看插件版本。

**Comment by waliu** [comment]
![image](https://user-images.githubusercontent.com/23111924/75086474-8471c200-556f-11ea-9385-8f5c9cf8aa91.png)
插件版本查看
