### ISSUE TITLE
将GaoDeLocation放到module.ts里面的provider里面的时候报错

### ISSUE THREAD

**Issue by GuShiwei** [waliu/cordova-plugin-gaodelocation-chenyu#2]
将GaoDeLocation放到module.ts里面的provider里面的时候一直报这个错：
    不能将类型“GaoDeLocationOriginal”分配给类型“Provider”。
    Type 'GaoDeLocationOriginal' is missing the following properties from type 'FactoryProvider': provide, 
    useFactory [2322]

**Comment by waliu** [comment]
因为ionic4 做了升级。ionic3 使用ionic native。会出现错误。考虑直接使用js定位 (<any>window).GaoDe.getCurrentPosition(successCallback, failedCallback);
