### ISSUE TITLE
ionic5 定位失败

### ISSUE THREAD

**Issue by ranlu823** [waliu/cordova-plugin-gaodelocation-chenyu#22]
仅返回 {“status”:"定位失败"}
插件版本：
"cordova-plugin-gaodelocation-chenyu":"^2.0.4"

Ionic:

   Ionic CLI                     : 5.4.16 
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

 (D:\Android\android-sdk).2.5
   NodeJS            : v12.16.1 (D:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10

**Comment by waliu** [comment]
在 catch 捕获异常。
