### ISSUE TITLE
ionic中无法传参

### ISSUE THREAD

**Issue by liuyao552** [waliu/cordova-plugin-gaodelocation-chenyu#23]
全是默认参数吗？是最准确的模式吗？相差了100米左右了

**Comment by liuyao552** [comment]
android精度就是100米。。。有时候很准，大多时候偏差100米

**Comment by waliu** [comment]
使用2.0.5 可以传参数。2.0.4 需要修改java里面代码。参数没有提出来公用

**Comment by waliu** [comment]
使用2.0.5 可以传参数。2.0.4 需要修改java里面的代码。
