### ISSUE TITLE
安装该插件2.0.5后安卓包不能打包成功

### ISSUE THREAD

**Issue by ron-zhao** [waliu/cordova-plugin-gaodelocation-chenyu#24]
**描述错误**
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:app:processReleaseResources
:app:generateReleaseSources
:app:javaPreCompileRelease
:app:compileReleaseJavaWithJavac/Users/xufeng/project/position/DL-APP/platforms/android/app/src/main/java/com/chenyu/GaoDeLocation/SerialLocation.java:236: 错误: 找不到符号
                .setSmallIcon(R.mipmap.ic_launcher)
对错误的清晰而简洁的描述。
不能打包Android包
**重现bug**
安装该插件2.0.5后不能打包安卓包
再现行为的步骤：

**预期行为**

对你期望发生的事情的清晰而简明的描述。

希望打包Android成功
**插件版本（请填写以下信息）：**

-android平台（cordova-android）：[例如7.0.0]
"cordova-android": "^7.1.4"    ionic3
-ios平台（cordova-ios）：[例如4.5.0]

-cordova插件版本[例如2.0.0]
cordova v8.1.0
**智能手机（请填写以下信息）：**

-设备：[例如iPhone6]

-操作系统：[例如iOS8.1]

-版本[例如22]

**附加上下文**

在此处添加有关此问题的任何其他上下文。

**Comment by waliu** [comment]
R.mipmap.ic_launcher  是指app的图标。他没有找到了图标。

**Comment by ron-zhao** [comment]
我卸载这插件就能打包成功且有图标的    安装就不行  我可以按什么思路去检查呢  谢谢

**Comment by ron-zhao** [comment]
> R.mipmap.ic_launcher 是指app的图标。他没有找到了图标。

我卸载这插件就能打包成功且有图标的 安装就不行 我可以按什么思路去检查呢 谢谢

**Comment by waliu** [comment]
你先加群找我。

**Comment by waliu** [comment]
390736068
