### ISSUE TITLE
欢迎ios单次定位报错需要开background mode

### ISSUE THREAD

**Issue by dennisexp** [waliu/cordova-plugin-gaodelocation-chenyu#25]
首先感谢作者为我们提供这个定位插件。
我在ionic中只用this.gaoDeLocation.getCurrentPosition这个方法定位，因苹果应用商店审核不允许使用background modes中的location updates，因为我没有后台持续都定位的使用场景。
到该页面时，就闪退，模拟机上提示的异常信息是让我开后台location updates.
 
总之，勾选了这个location updates就正常，不勾选就闪退。 
 
 但是勾选了的话，通不过苹果的审核。 
 
this.gaoDeLocation.getCurrentPosition光这个方法，似乎也不需要后台模式。

请问作者，是不是该插件默认需要开启后台模式？哪里能设置关闭吗？谢谢。

**Comment by waliu** [comment]
是的。默认要开启。审核的话，请看高德官网，有审核教程。

**Comment by waliu** [comment]
因为其他功能使用到了后台定位，我默认开启了后台定位。
