### ISSUE TITLE
安卓 定位失败 收到 code 200

### ISSUE THREAD

**Issue by myetear** [waliu/cordova-plugin-gaodelocation-chenyu#26]
安卓平台
在安卓手机上,我发现几乎无法收到 code 为 500 的错误信息,查看高德文档,使用的是 getErrorCode() == 0 判断的是否定位成功.
建议将 GaoDeLocation.java 239行的 代码更改为
```
  if (null != location && location.getErrorCode() == 0) {
```

**Comment by waliu** [comment]
改完代码直接pr给我。谢谢。

**Comment by myetear** [comment]
收到,我去学习一下怎么pr...
