### ISSUE TITLE
使用ionic

### ISSUE THREAD

**Issue by lordmos** [waliu/cordova-plugin-gaodelocation-chenyu#27]
**描述错误**

对错误的清晰而简洁的描述。

**重现bug**

再现行为的步骤：

**预期行为**

对你期望发生的事情的清晰而简明的描述。

**插件版本（请填写以下信息）：**

-android平台（cordova-android）：[例如7.0.0]

-ios平台（cordova-ios）：[例如4.5.0]

-cordova插件版本[例如2.0.0]

**智能手机（请填写以下信息）：**

-设备：[例如iPhone6]

-操作系统：[例如iOS8.1]

-版本[例如22]

**附加上下文**

在此处添加有关此问题的任何其他上下文。

**Comment by waliu** [comment]
请准确描述你的错误
