### ISSUE TITLE
返回的坐标系转为GPS

### ISSUE THREAD

**Issue by qdu123** [waliu/cordova-plugin-gaodelocation-chenyu#7]
我发觉高德拿到的位置信息不准，因此把插件的返回坐标转为gps坐标，拿到后用百度的js api逆编码，高德坐标系转gps坐标系的方法如下
//圆周率 GCJ_02_To_WGS_84
    double PI = 3.14159265358979324;
    /**
     * @author 作者:
     * 方法描述:方法可以将高德地图SDK获取到的GPS经纬度转换为真实的经纬度，可以用于解决安卓系统使用高德SDK获取经纬度的转换问题。
     * @param 需要转换的经纬度
     * @return 转换为真实GPS坐标后的经纬度
     * @throws <异常类型> {@inheritDoc} 异常描述
     */
    public HashMap<String, Double> delta(double lat,double lon) {
        double a = 6378245.0;//克拉索夫斯基椭球参数长半轴a
        double ee = 0.00669342162296594323;//克拉索夫斯基椭球参数第一偏心率平方
        double dLat = this.transformLat(lon - 105.0, lat - 35.0);
        double dLon = this.transformLon(lon - 105.0, lat - 35.0);
        double radLat = lat / 180.0 * this.PI;
        double magic = Math.sin(radLat);
        magic = 1 - ee * magic * magic;
        double sqrtMagic = Math.sqrt(magic);
        dLat = (dLat * 180.0) / ((a * (1 - ee)) / (magic * sqrtMagic) * this.PI);
        dLon = (dLon * 180.0) / (a / sqrtMagic * Math.cos(radLat) * this.PI);

        HashMap<String, Double> hm = new HashMap<String, Double>();
        hm.put("lat",lat - dLat);
        hm.put("lon",lon - dLon);

        return hm;
    }
    //转换经度
    public double transformLon(double x, double y) {
        double ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * Math.sqrt(Math.abs(x));
        ret += (20.0 * Math.sin(6.0 * x * this.PI) + 20.0 * Math.sin(2.0 * x * this.PI)) * 2.0 / 3.0;
        ret += (20.0 * Math.sin(x * this.PI) + 40.0 * Math.sin(x / 3.0 * this.PI)) * 2.0 / 3.0;
        ret += (150.0 * Math.sin(x / 12.0 * this.PI) + 300.0 * Math.sin(x / 30.0 * this.PI)) * 2.0 / 3.0;
        return ret;
    }
    //转换纬度
    public double transformLat(double x, double y) {
        double ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * Math.sqrt(Math.abs(x));
        ret += (20.0 * Math.sin(6.0 * x * this.PI) + 20.0 * Math.sin(2.0 * x * this.PI)) * 2.0 / 3.0;
        ret += (20.0 * Math.sin(y * this.PI) + 40.0 * Math.sin(y / 3.0 * this.PI)) * 2.0 / 3.0;
        ret += (160.0 * Math.sin(y / 12.0 * this.PI) + 320 * Math.sin(y * this.PI / 30.0)) * 2.0 / 3.0;
        return ret;
    }

**Comment by qdu123** [comment]
ios代码
#include <math.h>

//圆周率 GCJ_02_To_WGS_84
    double PI ;

/**
 * @author 作者:
 * 方法描述:方法可以将高德地图SDK获取到的GPS经纬度转换为真实的经纬度
 * @param 需要转换的经纬度
 * @return 转换为真实GPS坐标后的经纬度
 * @throws <异常类型> {@inheritDoc} 异常描述
 */
-(NSDictionary*) deltaWithLatAndLng:  (double) lat
                  lon: (double) lon {
    double a = 6378245.0;//克拉索夫斯基椭球参数长半轴a
    double ee = 0.00669342162296594323;//克拉索夫斯基椭球参数第一偏心率平方
    double dLat = [self transformLat:lon - 105.0 y: lat - 35.0];
    double dLon = [self transformLon:lon - 105.0 y:lat - 35.0 ];
    double radLat = lat / 180.0 * PI;
    double magic = sin(radLat);
    magic = 1 - ee * magic * magic;
    double sqrtMagic = sqrt(magic);
    dLat = (dLat * 180.0) / ((a * (1 - ee)) / (magic * sqrtMagic) * PI);
    dLon = (dLon * 180.0) / (a / sqrtMagic * cos(radLat) * PI);
    NSDictionary *dic= [[NSDictionary alloc]initWithObjectsAndKeys:[NSNumber    numberWithDouble:lat - dLat] , @"lat",
                        [NSNumber numberWithDouble:lon - dLon] , @"lon",nil];

    
    return dic;
}
//转换经度
-(double) transformLon: (double) x
    y:(double) y {
    double ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * sqrt(abs(x));
    ret += (20.0 * sin(6.0 * x * PI) + 20.0 * sin(2.0 * x * PI)) * 2.0 / 3.0;
    ret += (20.0 * sin(x * PI) + 40.0 * sin(x / 3.0 * PI)) * 2.0 / 3.0;
    ret += (150.0 * sin(x / 12.0 * PI) + 300.0 * sin(x / 30.0 * PI)) * 2.0 / 3.0;
    return ret;
}
//转换纬度
-(double) transformLat: (double) x
                     y:(double) y {
    double ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * sqrt(abs(x));
    ret += (20.0 * sin(6.0 * x * PI) + 20.0 *sin(2.0 * x * PI)) * 2.0 / 3.0;
    ret += (20.0 * sin(y * PI) + 40.0 * sin(y / 3.0 * PI)) * 2.0 / 3.0;
    ret += (160.0 * sin(y / 12.0 * PI) + 320 * sin(y * PI / 30.0)) * 2.0 / 3.0;
    return ret;
}

**Comment by qdu123** [comment]
此方法转自https://www.cnblogs.com/xinghuangroup/p/5787306.html

**Comment by waliu** [comment]
可设置为精确定位。详细请看插件源码

**Comment by qdu123** [comment]
> 可设置为精确定位。详细请看插件源码

我说的不准不是拿到的坐标不准，是逆编码得到的地址信息不准

**Comment by waliu** [comment]
你尝试打开wifi

**Comment by waliu** [comment]
如果还不准 ， 请修改定位的参数。可以调为精确定位。看你这边需要精确到什么程度。越精确，定位时间越久。
