### ISSUE TITLE
self.IOS_API_KEY  获取不到值

### ISSUE THREAD

**Issue by huangzhaoyi** [waliu/cordova-plugin-gaodelocation-chenyu#8]
self.IOS_API_KEY = [[self.commandDelegate settings] objectForKey:@"ios_api_key"];
    [AMapServices sharedServices].apiKey =self.IOS_API_KEY;
    // 带逆地理信息的一次定位（返回坐标和地址信息）
    [self configLocationManager];

self.IOS_API_KEY  获取不到值

**Comment by waliu** [comment]
请从新添加插件
